# Use the jenkins-agent for php 8.1
FROM prengineer/jenkins-agent-php-8.1:ARM64

LABEL mantainer="Jorge Pabón <pianistapr@hotmail.com>" description="A Test App that simulates a Calculator."

# Switch to the /App directory
WORKDIR /App

# Start the container with PHPUnit
ENTRYPOINT ["/bin/sh"]